# Generated by Django 5.1.4 on 2025-04-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customeruser_yearofstudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='school',
            field=models.CharField(choices=[('bs', 'Business School'), ('site', 'School of IT & Engineering'), ('seogi', 'School of Energy & Oil and Gas'), ('sg', 'School of Geology'), ('ise', 'International School of Economics'), ('kma', 'Kazakhstan Maritime Academy'), ('sam', 'School of Applied Mathematics'), ('sce', 'School of Chemical Engineering')], max_length=10),
        ),
    ]
